apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: learning-tracker-healthcheck
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: learning-tracker-frontend
